# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby for more details

version: 2.1
orbs:
  ruby: circleci/ruby@1.1.1
jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.0-node-browsers
        environment:
        - RACK_ENV=test
        - RAILS_ENV=test
        - DATABASE_URL=postgres://testuser:testpass@127.0.0.1:5432/mahbucket_test
        - SKIP_AUTH=true

      - image: circleci/postgres:10-alpine-ram
        environment:
          - POSTGRES_USER=testuser
          - POSTGRES_PASSWORD=testpass
          - POSTGRES_DB=mahbucket_test

    working_directory: ~/mahbucket

    steps:
      - checkout
      - ruby/install-deps

      - run:
          name: Set up database
          command: |
            bundle exec rake db:create db:schema:load

      - run:
          name: Brakeman
          command: bundle exec brakeman

      - ruby/rubocop-check
      - ruby/rspec-test
      - store_artifacts:
          path: ./log/
